In [1]:
import pandas as pd 
data = pd.read_pickle("../data/netflix/augmented_user_init_embedding")
data

{0: array([-0.00730934, -0.01081316, -0.00080739, ...,  0.00571171,
        -0.0097435 , -0.01719683]),
 1: array([-0.01337223, -0.00067123,  0.00434378, ...,  0.00758052,
        -0.00814754, -0.02604243]),
 2: array([-0.01774125, -0.00355707,  0.00285515, ...,  0.00245332,
        -0.01104759, -0.02810388]),
 3: array([-0.01597133, -0.00661114,  0.00463316, ...,  0.00480414,
        -0.01538129, -0.02963614]),
 4: array([-0.01328298,  0.00102894, -0.00019303, ...,  0.00580071,
        -0.00819761, -0.02487083]),
 5: array([-0.00471249,  0.00635266,  0.00742678, ..., -0.00664932,
        -0.01020927, -0.02719744]),
 6: array([-0.00935536, -0.00557645,  0.00405467, ..., -0.00289546,
        -0.00617563, -0.03025853]),
 7: array([-0.01789325, -0.00338301, -0.0059848 , ..., -0.00546512,
        -0.01199677, -0.03048782]),
 8: array([-0.00647197, -0.01644772, -0.00455422, ..., -0.00053559,
        -0.01409804, -0.02139585]),
 9: array([-0.01013731, -0.00890285, -0.00509884, ...,  0.005202

In [3]:
import numpy as np
data = np.load("../data/netflix/image_feat.npy")
data.shape

(17366, 512)

In [5]:
len(data["title"])


17366

In [12]:
# train_mat est la matrice de rating des items pas les utilisateurs
# shape : (nb_users, n_items) --> (13187,17366) 
# image_feat est la matrice des features des items de type image
# shape : (n_items, 2048) --> (17366, 512)
# text_feat est la matrice des features des items de type texte
# shape : (n_items, 300) --> (17366, 768)



In [25]:
# adj_mat est la matrice d'adjacence des items 
import scipy.sparse as sp
data = sp.load_npz("../data/netflix/s_adj_mat.npz")
data.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

137866

In [8]:
import numpy as np
data = np.load("../data/netflix/image_feat.npy")
data

array([[-0.15774503, -0.00716717,  0.4124675 , ...,  0.10390011,
        -0.01715323, -0.43209845],
       [ 0.23281592, -1.1583331 , -0.23480734, ..., -0.530654  ,
        -0.0779493 ,  0.21896783],
       [-0.27486238,  0.03133005,  0.35752466, ...,  0.20114578,
         0.08510679, -0.0212994 ],
       ...,
       [-0.59295464, -0.00548594, -0.20871714, ...,  0.28361988,
         0.23982379, -0.06477076],
       [-0.5923375 , -0.82194924, -0.3772713 , ...,  0.04306181,
         0.32266483, -0.30597824],
       [ 0.7699023 , -0.28032216,  0.13118505, ..., -0.10403652,
        -0.25480115, -0.15160449]], dtype=float32)

In [9]:
data.shape

(17366, 512)

In [2]:
data = np.load("../data/netflix/text_feat.npy")
data.shape

array([[-0.1732737 ,  0.04792119,  1.8007929 , ...,  0.07461055,
        -0.7846045 ,  0.11605124],
       [ 0.15666625, -0.65009135,  1.2494922 , ...,  0.30444208,
         0.3465191 ,  0.4527613 ],
       [-0.22203958,  0.06254917,  1.375786  , ..., -0.16560636,
         0.22444156, -0.33658004],
       ...,
       [-0.75080967, -0.47829783, -0.14537656, ...,  0.16172938,
         0.25817692, -0.81324416],
       [-0.82291645,  0.3318669 ,  1.4443554 , ..., -0.16108435,
         0.42525506,  0.09568702],
       [ 0.2284518 , -0.6483898 ,  1.3021019 , ...,  0.04782964,
         0.09555457, -0.11487633]], dtype=float32)

In [3]:
data.shape

(17366, 768)

In [6]:
import torch.nn as nn 

emb = nn.Embedding(5,embedding_dim=2)


In [2]:
import torch
imed = [1,2,3,4,5]
imed = torch.tensor(imed)
imed[[1,3]]

tensor([2, 4])

In [6]:
import numpy as np

# Votre dictionnaire
dict_array = {
    1: np.array([1, 2, 3]),
    2: np.array([4, 5, 6]),
    3: np.array([7, 8, 9])
}

# Convertir le dictionnaire en une liste d'arrays
list_of_arrays = list(dict_array.values())

# Convertir la liste d'arrays en un tableau numpy
numpy_array = np.stack(list_of_arrays)

print(numpy_array)
type(numpy_array[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

(8460, 1024)
(8460, 1024)
8460 items in daset
5422 users in daset


user  item
0      4486  7218
1       973  4137
2       262  8243
3      3690  8243
4      4550  1665
...     ...   ...
25623  3812  5551
25624  1767    53
25625  2735    53
25626  3161  5364
25627  4142  5364

[25628 rows x 2 columns]